import "./globals.css";
import Header from "@/app/components/Header";
import {ToastContainer} from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
    title: "Andrew Shop",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=block"
            />
            <link
                rel="stylesheet"
                href="https://kit-pro.fontawesome.com/releases/v5.15.1/css/pro.min.css"
            />
        </head>
        <body
            className=""
        >
        <div className="w-full fixed top-0 z-10 bg-white">
            <Header/>
        </div>
        <div className="mt-[80px]">
            {children}
        </div>
        <ToastContainer/>
        </body>
        </html>
    );
}
